### ISSUE TITLE
starter-apb stale

### ISSUE THREAD

**Issue by tchughesiv** [RHsyseng/container-rhel-examples#76]
@jcpowermac do we update it? or remove and point folks at apb-examples if Q's arise?  idk, _might_ be nice to have a starter image that's more of a template... but its just changing so rapidly.

**Comment by jcpowermac** [comment]
@tchughesiv or is the hello-world-apb sufficient?

**Comment by tchughesiv** [comment]
@jcpowermac so, you agree the apb-examples in fusor are sufficient examples? should remove ours or?

**Comment by tchughesiv** [comment]
addressed by https://github.com/RHsyseng/container-rhel-examples/pull/88
